version: '3'
services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ../Chat-Web-Fe
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - db
      - app